### ISSUE TITLE
package names

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SP18--RSurvival#1]
Post a list of candidate package names to decide on.

**Comment by viwilson** [comment]
survfuncs is what Ashley and I have in mind

**Comment by shannonpileggi** [comment]
yeah but funcs is so general...  EVERY package on CRAN consists of functions, but none of them have anything about functions in the name.  maybe incorporate something to do with parametric estimation?

**Comment by apjacobson** [comment]
survparam was our second option... other than that I'm stumped

**Comment by shannonpileggi** [comment]
Ok, so here are Hadley's guidelines:
http://r-pkgs.had.co.nz/package.html#naming

psf (parametric survival fit)
parmsurvfit (parametric survival fit)
psa (parametric survival analysis) 
survparmr (survival parametric r)
survparm (survival parametric)
parmsurv (parametric survival)
parmsurvr (parametric survival)

Anything standing out to you?
