### ISSUE TITLE
qqplot questions

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SP18--RSurvival#10]
It looks like the cdf of the observed data was computed ignoring the censored values, just using the complete values.  Is that correct? 

Did you look into if we should compute the cdf in a special way to adjust for censoring?

**Comment by apjacobson** [comment]
It doesn't plot the censored values, but it does use them to compute the cdf. The reason I did that is because I believe that's how minitab does it, but I could be wrong.

**Comment by shannonpileggi** [comment]
I am confused by this plot:

survfuncs::plot_qqsurv(melt, "logis", time = "T", censor = "C")

It appears that the axes range from 0-15, but the melt times are between 75-90 seconds.  Can you explain this?

**Comment by shannonpileggi** [comment]
Ah I should have realized that.  Then let's make both axes go from 0 - 100 by default to make it clearer.
