### ISSUE TITLE
plot_density modifications

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SP18--RSurvival#11]
- [x] re-name plot title "Weibull distribution", etc. (get rid of superimposed)
- [x] try to give the x-axis a meaningful scale like percents or counts
- [x] should we allow this function to take a by argument like your other functions?  for multiple groups, you could have the histogram appear in different colors and change the transparency so that you can see it.

**Comment by apjacobson** [comment]
I think if I add a by variable, then it might be best to produce a plot for each group. Because if there's like 5 levels to a by variable, you wouldn't want all 5 histograms and all 5 lines on one graph, it would be too crowded. Just a thought.

**Comment by shannonpileggi** [comment]
That is a good idea.

**Comment by apjacobson** [comment]
I already added it, it didn't take very long.
