### ISSUE TITLE
include data sets in package

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SP18--RSurvival#15]
firstdrink
graduate 
rearrest
aggressive

Anything else from class look interesting enough to include? 

We can also include this one from Lisa Oshita's summer research last summer:
https://data.mendeley.com/datasets/shfkj785yb/1

Please look up policies around including data, let's figure out what we need.

**Comment by shannonpileggi** [comment]
We can also include the oscars data set from Noelle Pablo's final project and the data from Victor's final project if there are no proprietary issues.    Noelle's Oscars data is in the data sets folder now.

**Comment by shannonpileggi** [comment]
Here is the description of Noelle's data:

The Academy Awards ceremony, the oldest entertainment awards show in the world, recognizes excellence in
the American film industry. For actors, being nominated or winning an Academy Award is widely considered
to be one of the highest honors an actor can receive, and many actors’ careers flourish after winning an award.
For this survival analysis study, we analyzed the time until some of the highest grossing actors in the world
receive their first Academy Award nomination. Of particular interest to this study is whether the hazard of
receiving an Academy Award nomination is associated with an actor’s gross earnings throughout his or her
career, gender, and number of film appearances.
The dataset contains data for the top 128 grossing actors up to 2017 as listed on Box Office Mojo. The
variables included are: the actor’s total adjusted gross earnings (in millions), the number of movies the
actor received credit for, the actor’s average gross earnings per movie, the actor’s top gross earnings from a
single movie, the actor’s gender, the year of the actor’s first full film appearance, the year of the actor’s first
oscar nomination, and the number of years between the actor’s first full film appearance and their first oscar
nomination.The data for the first film appearance and for the first oscar nomination was taken from IMDb.
The time-to-event random variable is the number of years from the actor’s first film appearance until his or
her first oscar nomination.
It should be noted that of the 128 observations in the data set, 48 were right-censored. Right-censored
observations represent actors who have not received an oscar nomination by the year 2017 or actors that
died before 2017 without ever receiving an oscar nomination. For the censor variable ‘1’ represents complete
observations, actors who received an oscar nomination by the year 2017, and ‘0’ represents right-censored
observations.

**Comment by apjacobson** [comment]
Do you know which textbook firstdrink, graduate, and rearrest are from?

**Comment by shannonpileggi** [comment]
rearrest and aggressive are from this text book:
[https://www.amazon.com/Applied-Longitudinal-Data-Analysis-Occurrence/dp/0195152964](https://www.amazon.com/Applied-Longitudinal-Data-Analysis-Occurrence/dp/0195152964)

firstdrink and graduate were from national surveys.

firstdrink: National Comorbidity Survey (1990-1992)
graduate:  National Educational Longitudinal Survey (NELS) from 1988-2002

**Comment by shannonpileggi** [comment]
firstdrink data set:
Age = age at first drink
Censor = 1 means time is complete
Gender: 1 = male, 2 = female

**Comment by apjacobson** [comment]
Are the column names in the datasets supposed to be snake case like oscars and rearrest or camel case like firstdrink and graduate? I looked at the style guide but it didn't say anything about column names in a dataset I don't think

**Comment by shannonpileggi** [comment]
Let's make all data set names and all variable names lower case.  Also, call the oscars data "oscars" rather than "oscarsdata".

**Comment by shannonpileggi** [comment]
Also include the iFixit data set linked above.
