### ISSUE TITLE
Anderson Darling statistic

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SP18--RSurvival#16]
I have done some work with the AD statistic and I am closer but not done.  The scratch work is in AndersonDarling.R.  Here, I followed the computations in calculator type style from AndersonDarlingByHand.pdf.  I have gotten the computations to match for *complete* data only.  

When adding in censored data, I think there is one last modification to make in the empirical cdf.  Try computing it according to this website:  [http://www.engineeredsoftware.com/nasa/pe_median.htm](http://www.engineeredsoftware.com/nasa/pe_median.htm).  

Another helpful resource is this, which I think explains how the Minitab qqplot is produced: [https://weibull.com/hotwire/issue8/relbasics8.htm](https://weibull.com/hotwire/issue8/relbasics8.htm).

**Comment by apjacobson** [comment]
I've read over the website a few times, and I'm still trying to understand it. So, are all the complete times supposed to come before all the censored times when sorting them, like in their example? And I guess I'm also just confused about what the increment equation is supposed to be? In their example they have round numbers in the I and O columns but if you calculate it, its supposed to have decimals, unless I'm doing something wrong.

**Comment by shannonpileggi** [comment]
I made some more updates to the AD code.  I am closer, but not quite there.  When I input the correct values of Fz obtained in minitab, I get the correct AD.  So we need to examine the computation of rank, AR, and Fz to see where we are going wrong.

**Comment by shannonpileggi** [comment]
See slide 50 [here](https://warwick.ac.uk/fac/sci/wmg/ftmsc/modules/modulelist/peuss/slides/section_8b_peussdistributions_2_slides_compatibility_mode.pdf) and see if you can match those computations.
