### ISSUE TITLE
package documentation

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/SP18--RSurvival#19]
- [x] Update package such that help file shows all functions and data sets.
- [x] Update package data set documentation is available for view.
- [x] Try the following commands to troubleshoot and view as a user:
```
library(devtools)
devtools::install_github("shannonpileggi/SP18--RSurvival/parmsurvfit", build_vignettes = TRUE)
library(parmsurvfit)
```

**Comment by apjacobson** [comment]
I tried installing it on both my computer (windows) and my roommate's computer (mac) and have no issues with any of the help files.
